# SELECT ID, CASE WHEN SIZE_OF_COLONY <= 25 and SIZE_OF_COLONY >= 0 THEN 'CRITICAL'
# WHEN SIZE_OF_COLONY <= 50 and SIZE_OF_COLONY >= 26 THEN 'HIGH'
# WHEN SIZE_OF_COLONY <= 75 and SIZE_OF_COLONY >= 51 THEN 'MEDIUM'
# WHEN SIZE_OF_COLONY <= 100 and SIZE_OF_COLONY >= 76 THEN 'LOW'
# END AS COLONY_NAME
# FROM ECOLI_DATA ORDER BY ID
SELECT A.ID, CASE
    WHEN A.PER <= 0.25 THEN 'CRITICAL'
    WHEN A.PER <= 0.5 THEN 'HIGH'
    WHEN A.PER <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME FROM 
(
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) as PER
    FROM ECOLI_DATA
) as A
ORDER BY ID
