# MEMBER_PROFILE, REST_REVIEW - MEMBER_ID
SELECT M.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE FROM MEMBER_PROFILE M 
JOIN REST_REVIEW A ON M.MEMBER_ID = A.MEMBER_ID
WHERE M.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT 
